/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: niallplatt (https://sketchfab.com/niallplatt)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/oil-tanker-b4aa7dcf31ca476dbc1ebcab94ca8cdc
title: Oil Tanker
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/ship.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.initialShadingGroup} />
      </group>
    </group>
  );
}

useGLTF.preload('/ship.gltf');
